[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.15.0"
rand = "0.8"
winit = "0.29"
winit_input_helper = "0.15"
crossbeam = "0.8"
crossbeam-channel = "0.5.15"
